# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'TealiumAppsFlyerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumAppsFlyerExample
  #!!!! Note: Change below to TealiumAppsflyer
  pod 'TealiumAppsFlyer', '~> 1.0'
  pod 'tealium-swift/TealiumLogger', '~> 1.9'
  pod 'tealium-swift/TealiumTagManagement', '~> 1.9'
  pod 'tealium-swift/TealiumAppData', '~> 1.9'
  pod 'tealium-swift/TealiumDeviceData', '~> 1.9'
  pod 'tealium-swift/TealiumLifecycle', '~> 1.9'
end
