# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'TealiumAppsFlyerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumAppsFlyerExample
  pod 'TealiumAppsFlyer',  :git => 'https://github.com/af-obodovskyi/tealium-ios-appsflyer-remote-command.git', :branch => 'master'
  pod 'tealium-swift/TealiumLogger', '~> 1.9'
  pod 'tealium-swift/TealiumTagManagement', '~> 1.9'
  pod 'tealium-swift/TealiumAppData', '~> 1.9'
  pod 'tealium-swift/TealiumDeviceData', '~> 1.9'
  pod 'tealium-swift/TealiumLifecycle', '~> 1.9'
end
